Add test for base64 encoded images
jordandobson/Framer pull request #2
Opened 2016-09-29 08:47 UTC by marckrenn

2016-09-29 20:48 UTC, eelco requested changes
One tiny thing that I’d change. (I don’t mean to be harsh about it, mostly just playing with Githubs new review feature ;)

2016-09-29 20:48 UTC, eelco commented on test/tests/LayerTest.coffee
> +			prefix = "../"
I think the prefix should be dropped, that does not make sense for a data image.

2016-09-29 20:48 UTC, eelco commented on test/tests/LayerTest.coffee
> +			imagePath = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEwAAABMBAMAAAA1uUwYAAAAAXNSR0IArs4c6QAAABVQTFRFKK/6LFj/g9n/lNf9lqz/wez/////Ke+vpgAAAK1JREFUSMft1sENhDAMBdFIrmBboAjuaWFrsNN/CRwAgUPsTAH55
Nice image ;)

2016-09-29 21:12 UTC, merged

2016-09-30 00:16 UTC, jordandobson commented on test/tests/LayerTest.coffee
> +			imagePath = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEwAAABMBAMAAAA1uUwYAAAAAXNSR0IArs4c6QAAABVQTFRFKK/6LFj/g9n/lNf9lqz/wez/////Ke+vpgAAAK1JREFUSMft1sENhDAMBdFIrmBboAjuaWFrsNN/CRwAgUPsTAH55
Heh. I added a few others for testing as well. 💃

2016-09-30 00:16 UTC, jordandobson commented on test/tests/LayerTest.coffee
> +			prefix = "../"
Totally... I removed it in following commits.

2016-09-30 08:16 UTC, marckrenn commented on test/tests/LayerTest.coffee
> +			prefix = "../"
In my defense, I wasn't 100% sure of the prefix's role in the context of a test, so I decided to simply keep it :)

Sorry!